[project]
name = "bobtkv3"
version = "0.1.0"
description = "Bob."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyaudio>=0.2.14",
    "python-dotenv>=1.2.1",
    "pyttsx3>=2.99",
    "requests>=2.32.5",
    "speechrecognition>=3.14.4",
    "tkinterdnd2>=0.4.3",
]
